/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jimmy Vargas' at '6/12/15 6:15 PM' with Gradle 2.4
 *
 * @author Jimmy Vargas, @date 6/12/15 6:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
