package com.salesforce.dev.pages.accounts;

/**
 * Created by mijhailvillarroel on 7/28/2016.
 */
public enum AccountSteps {

    ACCOUNT_NAME,
    PARENT_ACCOUNT,
    ACCOUNT_NUMBER,
    ACCOUNT_SITE,
    ACCOUNT_TYPE,
    ACCOUNT_INDUSTRY,
    ACCOUNT_ANNUAL_REVENUE,
    ACCOUNT_RATING,
    ACCOUNT_PHONE,
    ACCOUNT_FAX,
    ACCOUNT_WEBSITE,
    ACCOUNT_THICKER,
    ACCOUNT_OWNER_SHIP,
    ACCOUNT_EMPLOYEES,
    ACCOUNT_SICCODE,

//ADDRESSADDRESS INFORMATION

    ACCOUNT_BILLING_STREET,
    ACCOUNT_BILLING_CITY,
    ACCOUNT_BILLING_STATE,
    ACCOUNT_BILLING_ZIP,
    ACCOUNT_BILLING_COUNTRY,
    ACCOUNT_SHIPPING_STREET,
    ACCOUNT_SHIPPING_CITY,
    ACCOUNT_SHIPPING_STATE,
    ACCOUNT_SHIPPING_ZIP,
    ACCOUNT_SHIPPING_COUNTRY,

// ADDITIONAL INFORMATION

    ACCOUNT_CUSTOMER_PRIORITY,
    ACCOUNT_SLA_EXPIRATION_DATE,
    ACCOUNT_NUMBER_LOCATIONS,
    ACCOUNT_ACTIVE,
    ACCOUNT_SLA,
    ACCOUNT_SLASERIAL_NUMBER,
    ACCOUNT_UPSELL_OPPORTUNITY,

//DESCRIPTION INFORMATION

    ACCOUNT_DESCRIPTION


}
